# Generated by Django 3.1.1 on 2020-09-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.CharField(max_length=10, unique=True)),
                ('name_of_type', models.TextField()),
            ],
            options={
                'verbose_name': 'Типы оборудывания',
                'verbose_name_plural': 'Типы оборудывания',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10, unique=True)),
                ('code_of_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equpment', to='testtaskbackend.equipment_type')),
            ],
            options={
                'verbose_name': 'Оборудывание',
                'verbose_name_plural': 'Оборудывание',
            },
        ),
    ]
